### ISSUE TITLE
Error:	Connection timed out after 20 seconds of inactivity

### ISSUE THREAD

**Issue by mateors** [fclairamb/ftpserverlib#423]
**I got the following error**
```
level=warn component=server clientId=3 error="accept tcp [::]:2127: i/o timeout" event="Unable to open transfer"
level=warn component=server clientId=3 err="write tcp 172.21.131.5:21->172.21.128.1:61468: use of closed network connection" event="Couldn't flush line"
```

**Comment by drakkan** [comment]
Based on the previous error, I think the server cannot open an active connection. Can 172.21.131.5:21 connect to 172.21.128.1 on port 61468? If this is not allowed due to network configurations, there is nothing we can do in the library (please try to understand how active and passive FTP mode works). Thank you
