### ISSUE TITLE
WARNING: ASCII isn't correctly supported

### ISSUE THREAD

**Issue by shellus** [fclairamb/ftpserverlib#86]
I use windows explorer to open ftp://127.0.0.1:2121/

**Comment by worddevfr** [comment]
Can we have an explanation why the "ASCII" is not properly supported?
Are there any corrections planned for this?

**Comment by fclairamb** [comment]
Can you tell me where you are seeing this? Even if this message it's not supposed to pop-up as a warning anywhere.

It's not correctly supported because it doesn't respect the standard:
https://www.ietf.org/rfc/rfc959.txt
```
         3.1.1.1.  ASCII TYPE

            This is the default type and must be accepted by all FTP
            implementations.  It is intended primarily for the transfer
            of text files, except when both hosts would find the EBCDIC
            type more convenient.

            The sender converts the data from an internal character
            representation to the standard 8-bit NVT-ASCII
            representation (see the Telnet specification).  The receiver
            will convert the data from the standard form to his own
            internal form.

            In accordance with the NVT standard, the <CRLF> sequence
            should be used where necessary to denote the end of a line
            of text.  (See the discussion of file structure at the end
            of the Section on Data Representation and Storage.)

            Using the standard NVT-ASCII representation means that data
            must be interpreted as 8-bit bytes.

            The Format parameter for ASCII and EBCDIC types is discussed
            below.
```

But this standard makes very little sense for any current use of an FTP server. If someone has a use-case where the lack of proper ASCII support is an issue, I'll fix it.

**Comment by K4S1** [comment]
My use case:
```
ftp> open ftp.example.com
Connected to ftp.example.com.
220 example FTP
200 I'm in UTF8 only anyway
User (ftp.example.com:(none)): USER
331 OK
Password:
230 Password ok, continue
ftp>
ftp> Cd /Your/orders
250 CD worked on /Your/orders
ftp> lcd \\test.com\zf\c\alb\Here(W)\WebOrdre
Local directory now \\test.com\zf\c\alb\Here(W)\WebOrdre.
ftp>
ftp> mget *.txt
Could not list: failure
200 ASCII isn't properly supported: https://github.com/fclairamb/ftpserverlib/issues/86
Cannot find list of remote files.
```
Stopped working 2-3 days ago :-/

**Comment by drakkan** [comment]
Hi,

I added support for [ASCII mode](https://github.com/fclairamb/ftpserverlib/commit/2c0d6d8428a93ca41bd4992d8a7b8ba991a38424), so you should not see this warning anymore if you update to the latest version. 

However I think this isn't the issue here, `mget` should send a `NLST` command and we don't support wildcards while listing directories. I think this should work:

```
ftp> Cd /Your
250 CD worked on /Your
ftp> lcd \\test.com\zf\c\alb\Here(W)\WebOrdre
Local directory now \\test.com\zf\c\alb\Here(W)\WebOrdre.
ftp>
ftp> mget orders
```

are you saying wildcards worked before?

**Comment by K4S1** [comment]
I have used wildcard for years. 
With no issue,
issues started between the 21/01-2021 and today as I can confirm, on windows 10

Yes it works if I call file with full name.
But provider are doing random strings on the orders, so not sure how I should fix without wildcard without rebuilding. and not use this anymore.

**Comment by K4S1** [comment]
May be my provider that changed FTP server.. not sure here.

**Comment by drakkan** [comment]
ah ok, so you are not using this library yourself. Then you have to ask to your provider. This library simply passes "* .txt" to the implementer, so the wildcard logic could be handled downstream.

**Comment by K4S1** [comment]
No Sorry just relished, that this was a server lib :facepalm: 

Thanks for your input  you'll have a great weekend :-)
