### ISSUE TITLE
Async Stop()

### ISSUE THREAD

**Issue by adrianduke** [fclairamb/ftpserverlib#92]
It appears the behaviour of `server.Stop()` is asynchronous:

```go
func (t *testHarness) ScenarioCleanup(_ interface{}, _ error) {
	if t.FTPClient != nil {
		t.FTPClient.Quit()
	}
	if t.FTPServer != nil {
		t.FTPServer.Stop()
	}
```

Specifically I'm having issues whilst running my feature tests on circleci (however not on local), I often receive `dial tcp 127.0.0.1:2121: connect: connection refused` randomly in my tests, implying async shutdown when calling `server.Stop()`. I've tried adding delays with varying degrees of success (proportional to the delay size...). This however isn't ideal, slowing down tests is a problem.

```go
	if t.FTPServer != nil {
		t.FTPServer.Stop()
		// Fix for async shutdown
		time.Sleep(500 * time.Millisecond)
```

For the time being I can try randomise the port I'm using each time.

**Comment by fclairamb** [comment]
In my test unit what I do is to let the OS decide on which port the server shall listen and connect the clients to that. Which is better than randomness.

And I think it's because:
- The [TCPListener.Close()](https://golang.org/pkg/net/#TCPListener.Close) just informs the OS that it should release this opened port but [doesn't wait for it to be released](https://github.com/golang/go/issues/21856).
- My current implementation doesn't allow to wait for all clients to be disconnected before closing the listener. So it might be after the last client disconnects that the port can actually be released.

To be honest, I have seen that behavior with other programs and it might be quite standard. But I'm definitely interested in improving the code if you have an idea on how to do so.
